chore: quoting variables

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -1,23 +1,29 @@
 #!/bin/bash
 
-DOCKER_REGISTRY=quay.io
+# Check if docker is installed
+if [ ! "$(which docker)" -eq 0 ]; then
+    echo "Unable to find docker. Is it installed and added to your \$PATH?"
+    exit 1
+fi
 
+# Check if user is logged in to quay.io
+DOCKER_REGISTRY=quay.io
 docker pull ${DOCKER_REGISTRY}/typeform/gitleaks-config
 exit_code=$?
 
-# Check if user is logged in to quay.io
 if [ ! $exit_code -eq 0 ]; then
     echo "Unable to pull gitleaks container image. Are you logged in ${DOCKER_REGISTRY}?"
     exit 1
 fi
 
-if [ -z $GITHUB_WORKSPACE ]; then
+# If this is being ran as a Github ACtion use $GITHUB_WORKSPACE
+if [ -z "$GITHUB_WORKSPACE" ]; then
     repo_dir=$PWD
 else
     repo_dir=$GITHUB_WORKSPACE
 fi
 
-repo_name=$(basename $repo_dir)
+repo_name="$(basename "$repo_dir")"
 
 # Generate gitleaks configuration
 local_config=".gitleaks.toml"
@@ -26,9 +32,9 @@ gitleaks_config_container="${DOCKER_REGISTRY}/typeform/gitleaks-config"
 gitleaks_container="${DOCKER_REGISTRY}/typeform/gitleaks"
 
 # Generate the final gitleaks config file. If the repo has a local config, merge both
-if [ -f ./$local_config ]; then
+if [ -f ./"$local_config" ]; then
     docker container run --rm -v $repo_dir/$local_config:/app/$local_config \
-        $gitleaks_config_container python gitleaks_config_generator.py > $final_config
+    $gitleaks_config_container python gitleaks_config_generator.py > $final_config
 else
     docker container run --rm $gitleaks_config_container \
     python gitleaks_config_generator.py > $final_config
