test deploy

diff --git a/.github/workflows/graphql-generate-persisted-operations.yml b/.github/workflows/graphql-generate-persisted-operations.yml
--- a/.github/workflows/graphql-generate-persisted-operations.yml
+++ b/.github/workflows/graphql-generate-persisted-operations.yml
@@ -30,6 +30,19 @@ jobs:
           npm config set '//npm.pkg.github.com/:_authToken' ${{ secrets.GH_TOKEN }}
           npm config set @typeform:registry https://npm.pkg.github.com/
 
+      - name: Check if GraphQL endpoints are reachable
+        run: |
+          mapfile -t ENDPOINTS <<< "${GRAPHQL_ENDPOINTS}"
+          for url in "${ENDPOINTS[@]}"; do
+            echo "Pinging $url..."
+            curl_exit_code=0
+            curl --max-time 10 "$url?runNumber=$GITHUB_RUN_NUMBER" || curl_exit_code=$?
+            if [ $curl_exit_code -ne 0 ]; then
+              echo "❌ Curl command failed with exit code $curl_exit_code"
+              exit $curl_exit_code
+            fi
+          done
+
       - name: Install only @typeform/generate-persisted-operations-manifest
         run: yarn add --no-lockfile --non-interactive --dev @typeform/generate-persisted-operations-manifest
 
@@ -45,19 +58,6 @@ jobs:
         run: |
           echo "Contents of generated/persisted-query-manifest.json:"
           cat generated/persisted-query-manifest.json
-
-      - name: Check if GraphQL endpoints are reachable
-        run: |
-          mapfile -t ENDPOINTS <<< "${GRAPHQL_ENDPOINTS}"
-          for url in "${ENDPOINTS[@]}"; do
-            echo "Pinging $url..."
-            curl_exit_code=0
-            curl -v --max-time 10 "$url?runNumber=$GITHUB_RUN_NUMBER" || curl_exit_code=$?
-            if [ $curl_exit_code -ne 0 ]; then
-              echo "❌ Curl command failed with exit code $curl_exit_code"
-              exit $curl_exit_code
-            fi
-          done
 
       - name: Extract app name from package.json
         run: |
