feat(PLT-1044): manual registration of GetPublishedFormAndJobs

diff --git a/.github/workflows/graphql-generate-persisted-operations.yml b/.github/workflows/graphql-generate-persisted-operations.yml
--- a/.github/workflows/graphql-generate-persisted-operations.yml
+++ b/.github/workflows/graphql-generate-persisted-operations.yml
@@ -100,26 +100,26 @@ jobs:
       - name: Print extracted app name
         run: echo "Extracted APP_NAME is ${{ env.APP_NAME }}"
 
-      # - name: Upload manifest to internal allow list for all endpoints
-      #   run: |
-      #     mapfile -t ENDPOINTS <<< "${GRAPHQL_ENDPOINTS}"
-      #     curl_exit_code=0
-      #     for url in "${ENDPOINTS[@]}"; do
-      #       [[ -z "$url" ]] && continue  # skip empty lines
-      #       echo "Uploading manifest to $url/internal/operation-allow-list?deploymentRunNumber=$GITHUB_RUN_NUMBER&appName=${APP_NAME}"
-      #       curl --fail --max-time 30 -X PATCH "$url/internal/operation-allow-list?deploymentRunNumber=$GITHUB_RUN_NUMBER&appName=${APP_NAME}" \
-      #         -H "Content-Type: application/json" \
-      #         --data-binary "@generated/persisted-query-manifest.json"
+      - name: Upload manifest to internal allow list for all endpoints
+        run: |
+          mapfile -t ENDPOINTS <<< "${GRAPHQL_ENDPOINTS}"
+          curl_exit_code=0
+          for url in "${ENDPOINTS[@]}"; do
+            [[ -z "$url" ]] && continue  # skip empty lines
+            echo "Uploading manifest to $url/internal/operation-allow-list?deploymentRunNumber=$GITHUB_RUN_NUMBER&appName=${APP_NAME}"
+            curl --fail --max-time 30 -X PATCH "$url/internal/operation-allow-list?deploymentRunNumber=$GITHUB_RUN_NUMBER&appName=${APP_NAME}" \
+              -H "Content-Type: application/json" \
+              --data-binary "@generated/persisted-query-manifest.json"
 
-      #       if [ $? -ne 0 ]; then
-      #         echo "❌ Failed to upload manifest to $url"
-      #         curl_exit_code=1
-      #       else
-      #         echo "✅ Successfully uploaded to $url"
-      #       fi
-      #     done
+            if [ $? -ne 0 ]; then
+              echo "❌ Failed to upload manifest to $url"
+              curl_exit_code=1
+            else
+              echo "✅ Successfully uploaded to $url"
+            fi
+          done
 
-      #     if [ $curl_exit_code -ne 0 ]; then
-      #       echo "❌ One or more uploads failed, failing workflow"
-      #       exit $curl_exit_code
-      #     fi
+          if [ $curl_exit_code -ne 0 ]; then
+            echo "❌ One or more uploads failed, failing workflow"
+            exit $curl_exit_code
+          fi
