test deploy

diff --git a/.github/workflows/graphql-generate-persisted-operations.yml b/.github/workflows/graphql-generate-persisted-operations.yml
--- a/.github/workflows/graphql-generate-persisted-operations.yml
+++ b/.github/workflows/graphql-generate-persisted-operations.yml
@@ -7,7 +7,7 @@ on:
         required: true
 
 jobs:
-  generate:
+  update-allow-list:
     runs-on: [self-hosted, ci-universal]
     env:
       GRAPHQL_ENDPOINTS: |
@@ -30,18 +30,18 @@ jobs:
           npm config set '//npm.pkg.github.com/:_authToken' ${{ secrets.GH_TOKEN }}
           npm config set @typeform:registry https://npm.pkg.github.com/
 
-      # - name: Check if GraphQL endpoints are reachable
-      #   run: |
-      #     mapfile -t ENDPOINTS <<< "${GRAPHQL_ENDPOINTS}"
-      #     for url in "${ENDPOINTS[@]}"; do
-      #       echo "Pinging $url..."
-      #       curl_exit_code=0
-      #       curl --max-time 10 "$url?runNumber=$GITHUB_RUN_NUMBER" || curl_exit_code=$?
-      #       if [ $curl_exit_code -ne 0 ]; then
-      #         echo "❌ Curl command failed with exit code $curl_exit_code"
-      #         exit $curl_exit_code
-      #       fi
-      #     done
+      - name: Check if GraphQL endpoints are reachable
+        run: |
+          mapfile -t ENDPOINTS <<< "${GRAPHQL_ENDPOINTS}"
+          for url in "${ENDPOINTS[@]}"; do
+            echo "Pinging $url..."
+            curl_exit_code=0
+            curl --max-time 10 "$url?runNumber=$GITHUB_RUN_NUMBER" || curl_exit_code=$?
+            if [ $curl_exit_code -ne 0 ]; then
+              echo "❌ Curl command failed with exit code $curl_exit_code"
+              exit $curl_exit_code
+            fi
+          done
 
       - name: Install only @typeform/generate-persisted-operations-manifest
         run: yarn add --no-lockfile --non-interactive --dev @typeform/generate-persisted-operations-manifest
